# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-02 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=20, verbose_name='车位名字')),
                ('is_occupied', models.CharField(choices=[('1', '正在使用'), ('0', '空位')], default='0', max_length=5, verbose_name='是否被占用')),
            ],
            options={
                'verbose_name': '车位信息',
                'verbose_name_plural': '车位信息',
            },
        ),
    ]
