# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-02 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_auto_20180402_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='carposition',
            name='price',
            field=models.IntegerField(default=2, max_length=5, verbose_name='价格/小时'),
        ),
    ]
