# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-02 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_carposition_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carposition',
            name='is_occupied',
            field=models.CharField(choices=[('1', '正在使用'), ('0', '空位')], default='0', max_length=5, verbose_name='是否被占用'),
        ),
        migrations.AlterField(
            model_name='carposition',
            name='price',
            field=models.IntegerField(default=2, verbose_name='价格/小时'),
        ),
    ]
