# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-31 05:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_poems', '0010_auto_20180529_2345'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(verbose_name='评论内容')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_poems.Poems', verbose_name='评论诗词')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
        ),
    ]
