# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-18 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobboleArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='文章标题')),
                ('create_date', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='发表时间')),
                ('front_image_url', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='封面图地址')),
                ('url', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='文章链接')),
                ('url_object_id', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='url_id')),
                ('praise_nums', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='点赞数')),
                ('comment_nums', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='评论数')),
                ('fav_nums', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='收藏数')),
                ('tags', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='标签')),
                ('content', models.TextField(blank=True, default='', null=True, verbose_name='文章内容')),
            ],
            options={
                'verbose_name_plural': '伯乐在线文章',
                'verbose_name': '伯乐在线文章',
            },
        ),
    ]
