# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-20 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20180420_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogMessage',
        ),
    ]
