# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-20 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(default='', max_length=100, verbose_name='历史搜索')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
