# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-20 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logmessage',
            options={'ordering': ('-date',), 'verbose_name': '历史查询', 'verbose_name_plural': '历史查询'},
        ),
    ]
