# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-20 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_logmessage_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='搜索时间'),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='times',
            field=models.IntegerField(blank=True, null=True, verbose_name='查询次数'),
        ),
    ]
