# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='诗词名')),
                ('poem_type', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='体裁')),
                ('collection', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='作品集')),
                ('content', models.TextField(blank=True, default='', null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '诗词信息',
                'verbose_name': '诗词信息',
            },
        ),
    ]
