# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_poems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poems',
            name='explains',
            field=models.TextField(blank=True, default='', null=True, verbose_name='原文解释'),
        ),
    ]
