# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_poems', '0002_poems_explains'),
    ]

    operations = [
        migrations.AddField(
            model_name='poems',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='poems',
            name='times',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='年代'),
        ),
    ]
