# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_poems', '0003_auto_20180529_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='poems',
            name='about_author',
            field=models.TextField(blank=True, default='', null=True, verbose_name='关于作者'),
        ),
    ]
