# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_poems', '0005_auto_20180529_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, default=0, max_length=50, null=True, verbose_name='作者'),
        ),
    ]
