# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_poems', '0006_auto_20180529_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='poems',
            name='author',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='all_poems.Author', verbose_name='诗人'),
        ),
    ]
