# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-31 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_poems', '0010_auto_20180529_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='poems',
            name='view_nums',
            field=models.IntegerField(default=0, verbose_name='浏览次数'),
        ),
    ]
