# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-03 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20180402_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='pay_money',
            field=models.IntegerField(default=0, max_length=12, verbose_name='取车付款金额'),
        ),
    ]
